title: El Rinc√≥n de Hattrick
description: "Estrategias y consejos para mejorar tus juveniles y gestionar tu selecci√≥n nacional en Hattrick."
author: elPatronHT

url: "https://rinconhattrick.github.io"
baseurl: ""

theme: null

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true

permalink: "/:categories/:title/"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-search

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .git/
  - .github/
  - .gitignore
  - vendor/
  - _site/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      lang: "es"
      layout: "post"

social:
  - name: WhatsApp
    url: "https://wa.me/qr/537E4GO72BHHB1"
    icon: "üì≤"
  - name: YouTube
    url: "https://www.youtube.com/@elPatronHT"
    icon: "‚ñ∂Ô∏è"
